### ISSUE TITLE
everything@1.4.1.1015: hash check failed

### ISSUE THREAD

**Issue by mister-glass** [ScoopInstaller/Extras#7567]
#### Scoop Configuration

```json
{
  "lastupdate": "2021-12-21T08:30:04.1821496+02:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "aria2-enabled": true
}
```

scoop update output

```powershell
Updating 'everything' (1.4.1.1009 -> 1.4.1.1015)
Downloading new version
Everything-1.4.1.1015.x64.zip (1,7 MB) [==========================================================================================================================================================================================] 100%
Checking hash of Everything-1.4.1.1015.x64.zip ... ok.
install-context.reg (796 B) [=====================================================================================================================================================================================================] 100%
Checking hash of install-context.reg ... ERROR Hash check failed!
App:         extras/everything
URL:         https://raw.githubusercontent.com/ScoopInstaller/Extras/master/scripts/everything/install-context.reg
First bytes: 57 69 6E 64 6F 77 73 20
Expected:    8dae88b926055e99ed6bc9f851bb684ef791cf5213638330e822e5a6c3b9a98f
Actual:      6b27de9e61ff039bf42cd07f4da23034c4678a8968403913ba29fa5c5a3b457a

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=everything%401.4.1.1015%3a+hash+check+failed
```

**Comment by asifm** [comment]
The problem doesn't seem to have been resolved. The bot seems to be prematurely closing the related issues. 

Below is my console log.

```
>scoop install everything
WARN  Purging previous failed installation of everything.
Uninstalling 'everything' ().
'everything' was uninstalled.
Installing 'everything' (1.4.1.1015) [64bit]
Loading Everything-1.4.1.1015.x64.zip from cache
Checking hash of Everything-1.4.1.1015.x64.zip ... ok.
install-context.reg (796 B) [==========================================================================================] 100%
Checking hash of install-context.reg ... ERROR Hash check failed!
App:         extras/everything
URL:         https://raw.githubusercontent.com/ScoopInstaller/Extras/master/scripts/everything/install-context.reg
First bytes: 57 69 6E 64 6F 77 73 20
Expected:    8dae88b926055e99ed6bc9f851bb684ef791cf5213638330e822e5a6c3b9a98f
Actual:      6b27de9e61ff039bf42cd07f4da23034c4678a8968403913ba29fa5c5a3b457a
```

**Comment by rashil2000** [comment]
Run `scoop update` and then try

**Comment by pol-** [comment]
I still have the exact same issue here.
`scoop update` does not fix it.
